---

#####=== configure ===#####

- block:
    - name: bash/zsh | setup | configure
      stat: path="{{ dircolors_path | dirname }}"
      register: dircolors_dir

    - name: bash/zsh | configure | dircolors file
      copy: src=dir_colors dest="{{ dircolors_path }}"
      become: "{{ dircolors_dir.stat.pw_name == 'root' }}"
      when: configuration_state != 'absent'

    - name: bash/zsh | configure | shell initialization
      blockinfile:
        dest: "{{ shell_profile }}"
        create: yes
        backup: yes
        state: "{{ configuration_state }}"
        marker: "{{ dircolors_marker }}"
        block: "eval $( dircolors -b \"{{ dircolors_path }}\" )"
  when: ansible_user_shell | match(".*\/(bash|zsh)")
  tags:
    - bootstrap
    - configure
    - update

- name: bash/zsh | configure | dircolors file
  file: path="{{ dircolors_path }}" state=absent
  when: (configuration_state == 'absent') and (ansible_user_shell | match(".*\/(bash|zsh)"))
  tags: update

# TODO: figure out what these do and add them to .zshrc after eval dircolors?
# zstyle ':completion:*:default' list-colors ${(s.:.)LS_COLORS}
# zstyle ':completion:*' list-colors ''

