---

- name: setup
  include_vars: "{{ ansible_user_shell | basename }}.yml"
  tags: always

#####=== install ===#####

- block:
    - name: setup | create configuration directory
      file: path="{{ dircolors_dest_file | dirname }}" state=directory follow=yes

    - name: install | create dircolors file
      copy: src=dircolors dest="{{ dircolors_dest_file }}"
      become: "{{ dircolors_become }}"
      when: dircolors_config_state != 'absent'

    - name: install | remove dircolors file
      file: path="{{ dircolors_dest_file }}" state=absent
      become: "{{ dircolors_become }}"
      when: (dircolors_config_state == 'absent')
  tags:
    - bootstrap
    - bootstrap_dircolors
    - install
    - install_dircolors

#####=== configure ===#####

- name: bash/zsh | configure | shell initialization
  blockinfile:
    dest: "{{ dircolors_shell_config_file }}"
    create: yes
    backup: yes
    state: "{{ dircolors_config_state }}"
    marker: "{{ dircolors_config_marker }}"
    insertbefore: BOF
    block: "{{ dircolors_config_block }}"
  when: ansible_user_shell | match(".*\/(bash|zsh)")
  tags:
    - bootstrap
    - bootstrap_dircolors
    - configure
    - configure_dircolors
