---

- name: setup
  include_vars: "{{ ansible_user_shell | basename }}.yml"
  tags: always

- include: "install_{{ dircolors_configure_state }}.yml"
  tags:
    - bootstrap
    - bootstrap_dircolors
    - install
    - install_dircolors

- include: "{{ item }}"
  with_first_found:
    - "configure_{{ ansible_user_shell | basename }}_{{ dircolors_configure_state }}.yml"
    - "configure_default.yml"
  tags:
    - bootstrap
    - bootstrap_dircolors
    - configure
    - configure_dircolors
